# Generated by Django 4.2.2 on 2023-12-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisdomwave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('teacher', 'Teacher'), ('principal', 'Principal'), ('admin', 'Admin')], max_length=20),
        ),
    ]
