# Generated by Django 4.2.2 on 2023-12-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisdomwave', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('parent_name', models.CharField(max_length=100)),
                ('relationship_to_student', models.CharField(max_length=50)),
                ('parent_contact_number', models.CharField(max_length=20)),
                ('parent_nid', models.CharField(max_length=50)),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_address', models.TextField()),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('admission_date', models.DateField()),
                ('graduation_date', models.DateField(blank=True, null=True)),
                ('class_grade', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=10)),
                ('roll_number', models.CharField(max_length=10)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('medications', models.TextField(blank=True, null=True)),
                ('emergency_contact_medical', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=20, null=True)),
                ('doctor_contact_info', models.TextField(blank=True, null=True)),
                ('conduct_grades', models.CharField(blank=True, max_length=5, null=True)),
                ('disciplinary_records', models.TextField(blank=True, null=True)),
                ('clubs_and_societies', models.TextField(blank=True, null=True)),
                ('sports_participation', models.TextField(blank=True, null=True)),
                ('achievements', models.TextField(blank=True, null=True)),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('id_card', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
