# Generated by Django 4.2.2 on 2023-12-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisdomwave', '0003_studentdetails_alter_customuser_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdetails',
            old_name='id_card',
            new_name='profile_p',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='pp'),
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='student_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
