# Generated by Django 4.2.2 on 2023-12-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisdomwave', '0004_rename_id_card_studentdetails_profile_p_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('contact_phone', models.CharField(max_length=15)),
                ('contact_email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('qualifications', models.TextField()),
                ('subjects_taught', models.CharField(max_length=255)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('joining_date', models.DateField()),
                ('department', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('job_role', models.CharField(max_length=50)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='teacher_profiles/')),
                ('facebook', models.CharField(max_length=50)),
                ('twitter', models.CharField(max_length=50)),
                ('instagrame', models.CharField(max_length=50)),
                ('whatsapp', models.CharField(max_length=50)),
                ('youtube', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='employee_id',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
