# Generated by Django 4.2.2 on 2023-12-15 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wisdomwave', '0005_teacherdetails_customuser_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherdetails',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
