# Generated by Django 4.2.2 on 2023-12-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisdomwave', '0006_alter_teacherdetails_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='class_grade',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='conduct_grades',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='section',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teacherdetails',
            name='facebook',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='teacherdetails',
            name='instagrame',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='teacherdetails',
            name='twitter',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='teacherdetails',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='teacherdetails',
            name='youtube',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
