# Generated by Django 4.2.7 on 2023-12-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisdomwave', '0007_alter_studentdetails_class_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_exam_name', models.CharField(max_length=100)),
                ('exam_name', models.CharField(max_length=100)),
                ('exam_date', models.DateField()),
                ('exam_start_date', models.DateField()),
                ('exams_availability', models.BooleanField(default=True)),
                ('details_of_exam', models.TextField()),
                ('registration_start_date', models.DateField()),
                ('registration_end_date', models.DateField()),
                ('max_marks', models.PositiveIntegerField()),
                ('pass_marks', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='pp')),
                ('school_location', models.CharField(max_length=255)),
                ('school_slogan', models.CharField(max_length=500)),
                ('school_email', models.EmailField(max_length=254)),
                ('school_contacts', models.CharField(max_length=100)),
                ('about_school', models.TextField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('whatsapp_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
