# Generated by Django 4.2.7 on 2023-12-28 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisdomwave', '0008_examdetails_schoolinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examdetails',
            name='exam_start_date',
        ),
        migrations.AddField(
            model_name='examdetails',
            name='exam_time',
            field=models.TimeField(default=datetime.time(12, 42, 33, 516013)),
            preserve_default=False,
        ),
    ]
