# Generated by Django 4.2.7 on 2023-12-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisdomwave', '0009_remove_examdetails_exam_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherdetails',
            name='classteacher',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='school_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo'),
        ),
    ]
