# Generated by Django 4.2.7 on 2023-12-29 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wisdomwave', '0010_teacherdetails_classteacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examdetails',
            name='max_marks',
        ),
        migrations.RemoveField(
            model_name='examdetails',
            name='pass_marks',
        ),
    ]
