# Generated by Django 4.2.7 on 2023-12-29 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wisdomwave', '0011_remove_examdetails_max_marks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='class_Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classess', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacherdetails',
            name='full_name',
        ),
        migrations.CreateModel(
            name='sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec', models.CharField(max_length=100)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='wisdomwave.class_grade')),
            ],
        ),
    ]
