# Generated by Django 4.2.2 on 2024-01-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisdomwave', '0012_class_grade_remove_teacherdetails_full_name_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherdetails',
            name='employee_id',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
