# Generated by Django 4.2.2 on 2024-01-02 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wisdomwave', '0013_teacherdetails_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sections',
            old_name='grade',
            new_name='class_grade',
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('class_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_name', to='wisdomwave.class_grade')),
            ],
        ),
    ]
