# Generated by Django 4.2.2 on 2024-01-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisdomwave', '0014_rename_grade_sections_class_grade_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='class_grade',
        ),
        migrations.AddField(
            model_name='subject',
            name='class_grade',
            field=models.ManyToManyField(related_name='subject_name', to='wisdomwave.class_grade'),
        ),
    ]
