# Generated by Django 4.2.2 on 2024-01-07 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wisdomwave', '0015_remove_subject_class_grade_subject_class_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.IntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wisdomwave.examdetails')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wisdomwave.studentdetails')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wisdomwave.subject')),
            ],
        ),
    ]
