# Generated by Django 4.2.2 on 2024-01-09 20:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wisdomwave', '0016_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='stu_class',
            field=models.CharField(default='no_class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mark',
            name='stu_roll',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mark',
            name='stu_section',
            field=models.CharField(default='no_sec'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mark',
            name='marks_obtained',
            field=models.PositiveIntegerField(),
        ),
    ]
